name: CI Gate
on:
  pull_request:
    branches: ["main", "feature/**"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run ci
        uses: borales/actions-yarn@v4
        with:
          cmd: ci
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
